export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_LOADER_STATUS = "SET_LOADER_STATUS";

export const SET_NETWORK_ERRORS = 'SET_NETWORK_ERRORS'
export const CLEAR_NETWORK_ERRORS = 'CLEAR_NETWORK_ERRORS'
export const SET_UNAUTHORIZED_ERRORS = 'SET_UNAUTHORIZED_ERRORS'
export const CLEAR_UNAUTHORIZED_ERRORS = 'CLEAR_UNAUTHORIZED_ERRORS'
export const SET_INTERNAL_SERVER_ERRORS = 'SET_INTERNAL_SERVER_ERRORS'
export const CLEAR_INTERNAL_SERVER_ERRORS = 'CLEAR_INTERNAL_SERVER_ERRORS'

